name: Windows make

on:
  push:
    branches: [ main, master, development ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: "MINGW64"
      CHERE_INVOKING: 1
    name: MSYS2 MINGW64
    steps:
    - uses: actions/checkout@v2
    - name: Set up shell
      run: echo ::add-path::C:\msys64\usr\bin\
      shell: pwsh
    - name: Print system version
      run: |
        uname
    - run: mkdir -p build
    - run: cd build && cmake -G"MSYS Makefiles" ..
    - run: |
        cd build && make VERBOSE=1 || /mingw64/bin/g++.exe -O3 -DNDEBUG -shared -o liblsl.dll -Wl,--out-implib,liblsl.dll.a -Wl,--major-image-version,1,--minor-image-version,14 -Wl,--whole-archive CMakeFiles/lsl.dir/objects.a -Wl,--no-whole-archive  -lbcrypt -liphlpapi -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -lwinmm -lmswsock -lws2_32
    - name: make install
      run: make -C build install
    - name: upload install dir
      uses: actions/upload-artifact@master
      with:
        name: liblsl-windows
        path: build/install
