name: Windows make

on:
  push:
    branches: [ main, master, development ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: "MINGW64"
      CHERE_INVOKING: 1
    name: MSYS2 MINGW64
    steps:
    - uses: actions/checkout@v2
    - name: Set up shell
      run: echo ::add-path::C:\msys64\usr\bin\
      shell: pwsh
    - name: Print system version
      run: |
        uname
    - run: mkdir -p build
    - run: cd build && cmake -G"MSYS Makefiles" ..
    - run: |
        cd build && make || /mingw64/bin/c++.exe -O3 -DNDEBUG   -shared -Wl,--enable-auto-import -o msys-lsl.dll -Wl,--out-implib,liblsl.dll.a -Wl,--major-image-version,1,--minor-image-version,14 CMakeFiles/lsl.dir/src/buildinfo.cpp.o CMakeFiles/lslobj.dir/src/api_config.cpp.o CMakeFiles/lslobj.dir/src/cancellation.cpp.o CMakeFiles/lslobj.dir/src/cast.cpp.o CMakeFiles/lslobj.dir/src/common.cpp.o CMakeFiles/lslobj.dir/src/consumer_queue.cpp.o CMakeFiles/lslobj.dir/src/data_receiver.cpp.o CMakeFiles/lslobj.dir/src/info_receiver.cpp.o CMakeFiles/lslobj.dir/src/inireader.cpp.o CMakeFiles/lslobj.dir/src/inlet_connection.cpp.o CMakeFiles/lslobj.dir/src/loguru/loguru.cpp.o CMakeFiles/lslobj.dir/src/lsl_resolver_c.cpp.o CMakeFiles/lslobj.dir/src/lsl_inlet_c.cpp.o CMakeFiles/lslobj.dir/src/lsl_outlet_c.cpp.o CMakeFiles/lslobj.dir/src/lsl_streaminfo_c.cpp.o CMakeFiles/lslobj.dir/src/lsl_xml_element_c.cpp.o CMakeFiles/lslobj.dir/src/netinterfaces.cpp.o CMakeFiles/lslobj.dir/src/pugixml/pugixml.cpp.o CMakeFiles/lslobj.dir/src/resolver_impl.cpp.o CMakeFiles/lslobj.dir/src/resolve_attempt_udp.cpp.o CMakeFiles/lslobj.dir/src/sample.cpp.o CMakeFiles/lslobj.dir/src/send_buffer.cpp.o CMakeFiles/lslobj.dir/src/socket_utils.cpp.o CMakeFiles/lslobj.dir/src/stream_info_impl.cpp.o CMakeFiles/lslobj.dir/src/stream_outlet_impl.cpp.o CMakeFiles/lslobj.dir/src/tcp_server.cpp.o CMakeFiles/lslobj.dir/src/time_postprocessor.cpp.o CMakeFiles/lslobj.dir/src/time_receiver.cpp.o CMakeFiles/lslobj.dir/src/udp_server.cpp.o CMakeFiles/lslboost.dir/lslboost/asio_objects.cpp.o CMakeFiles/lslboost.dir/lslboost/libs/atomic/src/lockpool.cpp.o CMakeFiles/lslboost.dir/lslboost/libs/chrono/src/chrono.cpp.o CMakeFiles/lslboost.dir/lslboost/serialization_objects.cpp.o -lws2_32 -lwinmm -liphlpapi -lbcrypt -lmswsock
    - name: make install
      run: make -C build install
    - name: upload install dir
      uses: actions/upload-artifact@master
      with:
        name: liblsl-windows
        path: build/install
